---
version: "2.1"
services:
  libreoffice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreoffice
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 3000:3000
    volumes:
      - ./data:/data:z
    restart: unless-stopped
