---
version: "2.1"
services:
  localstack:
    image: localstack/localstack
    network_mode: bridge
    environment:
      SERVICES: sns,s3,sqs
      DEBUG: 0
    ports:
      - 4566:4566
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
